allure.results.directory=target/allure-results
allure.link.issue.pattern = https://jira.example.org/browse/{}
allure.testng.hide.disabled.tests = true
allure.testng.hide.configuration.failures = true
